# Generated by Django 2.1 on 2018-09-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
